ga(@fitness_gene,3,gaoptimset('PopulationType','custom','PopulationSize',10,'CreationFcn',@creating_gene3))
 ga(@fitness_gene,3,gaoptimset('PopulationType','custom','PopulationSize',10,'CreationFcn',@creating_gene3,'CrossoverFcn',@crossover_gene))
  
 ga(@fitness_gene,2,gaoptimset('PopulationType','custom','PopulationSize',20,'CreationFcn',...
     @creating_gene3,'CrossoverFcn',@crossover_gene3,'MutationFcn',@mutation_gene3,'Vectorized','on',...
     'UseParallel','always'))
 
 
  ga(@fitness_gene,1,gaoptimset('PopulationType','custom','PopulationSize',6,'CreationFcn',...
      @creating_gene3,'CrossoverFcn',@crossover_gene3,'MutationFcn',@mutation_gene3,'Vectorized','on',...
      'UseParallel','always','PlotFcn',@plot_gene,'Elitecount',2,'CrossoverFraction',1))
  
  
  ga(@fitness_gene,1,gaoptimset('PopulationType','custom','PopulationSize',6,'CreationFcn',...
      @creating_gene3,'CrossoverFcn',@crossover_gene3,'MutationFcn',@mutation_gene3,'Vectorized','off',...
      'UseParallel','always','PlotFcn',{@plot_gene,@gaplotbestf,@gaplotscores,@gaplotstopping},'Elitecount',2,'CrossoverFraction',0.8,'Generations',50))
  
  
  ga(@fitness_gene,1,[],[],[],[],[],[],[],[],gaoptimset('PopulationType','custom','PopulationSize',150,'CreationFcn',...
      @creating_gene3,'CrossoverFcn',@crossover_gene3,'MutationFcn',@mutation_gene3,'Vectorized','off',...
      'PlotFcn',{@gaplotbestf,@gaplotselection,@gaplotstopping,@gaplotscores},'Elitecount',1,'CrossoverFraction',0.5,'Generations',10,'UseParallel','Always'))
  
 
   ga(@(gene) fitness_gene_vectorized(gene,N_box),1,[],[],[],[],[],[],[],[],gaoptimset('PopulationType','custom','PopulationSize',150,'CreationFcn',...
      @creating_gene3,'CrossoverFcn',@crossover_gene3,'MutationFcn',@mutation_gene3,'Vectorized','off',...
      'PlotFcn',{@gaplotbestf,@gaplotselection,@gaplotstopping,@gaplotscores},'Elitecount',1,'CrossoverFraction',0.5,'Generations',10,'UseParallel','Always'))
  
  
  [x,feval]=ga(@(gene) fitness_gene_vectorized(gene,'receptor.C.map'),1,[],[],[],[],[],[],[],[],gaoptimset('PopulationType','custom','PopulationSize',150,'CreationFcn',...
      @creating_gene3,'CrossoverFcn',@crossover_gene5,'MutationFcn',@mutation_gene3,'Vectorized','off',...
      'PlotFcn',{@gaplotbestf,@gaplotselection,@gaplotstopping,@gaplotscores},'Elitecount',1,'CrossoverFraction',0.5,'Generations',10,'UseParallel','Always','HybridFcn',{@fminunc}))
  
   [x,feval]=ga(@(gene) fitness_gene_vectorized(gene,'receptor.C.map'),1,[],[],[],[],[],[],[],[],gaoptimset('PopulationType','custom','PopulationSize',150,'CreationFcn',...
      @(a,b,c) creating_gene3(a,b,c,[10 10 10]),'CrossoverFcn',@crossover_gene5,'MutationFcn',@mutation_gene4,'Vectorized','off',...
      'PlotFcn',{@gaplotbestf,@gaplotselection,@gaplotstopping,@gaplotscores},'Elitecount',1,'CrossoverFraction',0.5,'Generations',10,'UseParallel','Always','HybridFcn',{@fminunc}))
  

  
   [x,feval]=simulannealbnd(@(A) simulated_pos_quat(A,gene1,'receptor.C.map'),[45.686 46 18.443 0 0 0 ],[lb(1:3), 0 0 0],[ub(1:3),360 360 360], saoptimset('InitialTemperature',[100],'TemperatureFcn',@temperaturefast,'PlotFcns',{@saplotbestf,@saplottemperature,@saplotf,@saplotstopping})) 
 
   [gene,score]=ga_make_2(10,[1,2,1],'c:\_malaria_research\matlab_fact\2AAW_receptor.C.map',...
     'c:\_malaria_research\matlab_fact\2AAW_receptor.OA.map',...
     'c:\_malaria_research\matlab_fact\2AAW_receptor.N.map',...
     'c:\_malaria_research\matlab_fact\2AAW_receptor.HD.map',...
     'c:\_malaria_research\matlab_fact\2AAW_receptor.e.map')
 
 [gene,score]=ga_make_3(10,[1,2,1],'D:\MATLAB\ttt\grid_factory\box4\box4.C.map',...
     'D:\MATLAB\ttt\grid_factory\box4\box4.OS.map',...
     'D:\MATLAB\ttt\grid_factory\box4\box4.NS.map',...
     'D:\MATLAB\ttt\grid_factory\box4\box4.HD.map',...
     'D:\MATLAB\ttt\grid_factory\box4\box4.e.map')
  
 [gene,score]=ga_make_2(10,[1,2,1],'D:\MATLAB\ttt\grid_factory\thesis\GLN\optim_aligned_1.C.map',...
     'D:\MATLAB\ttt\grid_factory\thesis\GLN\optim_aligned_1.OA.map',...
     'D:\MATLAB\ttt\grid_factory\thesis\GLN\optim_aligned_1.N.map',...
     'D:\MATLAB\ttt\grid_factory\thesis\GLN\optim_aligned_1.HD.map',...
     'D:\MATLAB\ttt\grid_factory\thesis\GLN\optim_aligned_1.e.map')
  
 [gene,score]=ga_make_3(10,[1,2,1],'D:\MATLAB\ttt\grid_factory\thesis\GLN\optim_aligned_1.C.map',...
     'D:\MATLAB\ttt\grid_factory\thesis\GLN\optim_aligned_1.OA.map',...
     'D:\MATLAB\ttt\grid_factory\thesis\GLN\optim_aligned_1.N.map',...
     'D:\MATLAB\ttt\grid_factory\thesis\GLN\optim_aligned_1.HD.map',...
     'D:\MATLAB\ttt\grid_factory\thesis\GLN\optim_aligned_1.e.map')  
 
 [gene,score]=ga_make_3(12,[1,1,1],'D:\MATLAB\ttt\grid_factory\thesis\GLN\optim_aligned_1.C.map',...
     'D:\MATLAB\ttt\grid_factory\thesis\GLN\optim_aligned_1.OA.map',...
     'D:\MATLAB\ttt\grid_factory\thesis\GLN\optim_aligned_1.N.map',...
     'D:\MATLAB\ttt\grid_factory\thesis\GLN\optim_aligned_1.HD.map',...
     'D:\MATLAB\ttt\grid_factory\thesis\GLN\optim_aligned_1.e.map')  %%%OK
 
 
 [gene,~]=ga_make_4(12,[1,1,1],'D:\MATLAB\ttt\grid_factory\thesis\GLN\optim_aligned_1.C.map',...
     'D:\MATLAB\ttt\grid_factory\thesis\GLN\optim_aligned_1.OA.map',...
     'D:\MATLAB\ttt\grid_factory\thesis\GLN\optim_aligned_1.N.map',...
     'D:\MATLAB\ttt\grid_factory\thesis\GLN\optim_aligned_1.HD.map',...
     'D:\MATLAB\ttt\grid_factory\thesis\GLN\optim_aligned_1.e.map')  %%%OK 2018
 
 [gene,score]=ga_make_4(12,[1,1,1],'D:\MATLAB\ttt\grid_factory\thesis\GLN\optim_aligned_1.C.map',...
     'D:\MATLAB\ttt\grid_factory\thesis\GLN\optim_aligned_1.OA.map',...
     'D:\MATLAB\ttt\grid_factory\thesis\GLN\optim_aligned_1.N.map',...
     'D:\MATLAB\ttt\grid_factory\thesis\GLN\optim_aligned_1.HD.map',...
     'D:\MATLAB\ttt\grid_factory\thesis\GLN\optim_aligned_1.e.map')  %%%OK 2019
 
  [gene,score]=ga_make_4(12,2,2,[1,1,1],'D:\MATLAB\ttt\grid_factory\thesis\GLN\optim_aligned_1.C.map',...
     'D:\MATLAB\ttt\grid_factory\thesis\GLN\optim_aligned_1.OA.map',...
     'D:\MATLAB\ttt\grid_factory\thesis\GLN\optim_aligned_1.N.map',...
     'D:\MATLAB\ttt\grid_factory\thesis\GLN\optim_aligned_1.HD.map',...
     'D:\MATLAB\ttt\grid_factory\thesis\GLN\optim_aligned_1.e.map')  %%%OK 2021
 
 
 [gene,score]=ga_make_3(12,[1,1,1],'D:\MATLAB\ttt\grid_factory\thesis\GLN_CYS\optim_aligned_1.C.map',...
     'D:\MATLAB\ttt\grid_factory\thesis\GLN_CYS\optim_aligned_1.OA.map',...
     'D:\MATLAB\ttt\grid_factory\thesis\GLN_CYS\optim_aligned_1.N.map',...
     'D:\MATLAB\ttt\grid_factory\thesis\GLN_CYS\optim_aligned_1.HD.map',...
     'D:\MATLAB\ttt\grid_factory\thesis\GLN_CYS\optim_aligned_1.e.map')
 
  [gene,score]=ga_make_3(10,[1,1,2],'D:\MATLAB\ttt\grid_factory\thesis\GLN_CYS_GLY\optim_aligned_1.C.map',...
     'D:\MATLAB\ttt\grid_factory\thesis\GLN_CYS_GLY\optim_aligned_1.OA.map',...
     'D:\MATLAB\ttt\grid_factory\thesis\GLN_CYS_GLY\optim_aligned_1.N.map',...
     'D:\MATLAB\ttt\grid_factory\thesis\GLN_CYS_GLY\optim_aligned_1.HD.map',...
     'D:\MATLAB\ttt\grid_factory\thesis\GLN_CYS_GLY\optim_aligned_1.e.map') 
 
 [gene,score]=ga_make_3(10,[1,1,1],'D:\MATLAB\ttt\grid_factory\thesis\CYS\optim_aligned_1.C.map',...
     'D:\MATLAB\ttt\grid_factory\thesis\CYS\optim_aligned_1.OA.map',...
     'D:\MATLAB\ttt\grid_factory\thesis\CYS\optim_aligned_1.N.map',...
     'D:\MATLAB\ttt\grid_factory\thesis\CYS\optim_aligned_1.HD.map',...
     'D:\MATLAB\ttt\grid_factory\thesis\CYS\optim_aligned_1.e.map')

 
 child = crossover_mol_5ed( mol1,mol2,0,'D:\MATLAB\ttt\grid_factory\thesis\GLN\optim_aligned_1.C.map',...
     'D:\MATLAB\ttt\grid_factory\thesis\GLN\optim_aligned_1.OA.map',...
     'D:\MATLAB\ttt\grid_factory\thesis\GLN\optim_aligned_1.N.map',...
     'D:\MATLAB\ttt\grid_factory\thesis\GLN\optim_aligned_1.HD.map',...
     'D:\MATLAB\ttt\grid_factory\thesis\GLN\optim_aligned_1.e.map',[],[],[])  %design of crossover_mol_5ed
  /
  